name: GitHub Metrics

on:
  schedule: [{ cron: "0 6 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: joe-ton
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Los_Angeles

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: percentage

          plugin_achievements: yes
          plugin_achievements_display: compact

          plugin_lines: yes
          plugin_stars: yes
          plugin_followup: yes
          plugin_topics: yes
