name: GitHub Metrics

on:
  schedule: [{ cron: "0 6 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: joe-ton
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Los_Angeles

          # Optional plugins
          plugin_lines: yes
          plugin_stars: yes
          plugin_achievements: yes
          plugin_followup: yes
          plugin_topics: yes
